export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const SORT_USERS_BY_NAME = "SORT_USERS_BY_NAME";

export const REQUEST_LOADING = "LOADING";
export const REQUEST_FAILED = "REQUEST_FAILED";
